# Generated by Django 6.0.4 on 2026-05-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='dropoff_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='dropoff_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
