# Generated by Django 6.0.4 on 2026-05-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_riderequest_dropoff_lat_riderequest_dropoff_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
